Repository SwiGs1/GoodRadscorpion-F13, pull requests merged in 2020-07, with the labels that each got.

#4 Kebab fixes + fence fixes ,
  _maps/map_files/Pahrump/Pahrump.dmm
Labels: Mapping, Testmerged

#5 Mob Addition and Changes.
  code/datums/actions/stealthboy_cloaking.dm
  code/game/objects/items/stealthboy.dm
  code/modules/fallout/mob/simple_animal/mobs/Securitron.dm
  code/modules/fallout/mob/simple_animal/mobs/nightkin.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/living/simple_animal/hostile/chinese.dm
  code/modules/mob/living/simple_animal/hostile/raider.dm
  code/modules/mob/living/simple_animal/hostile/wasteanimals.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  icons/fallout/mobs/animal.dmi
  icons/fallout/mobs/nightkin.dmi
  icons/fallout/mobs/nightkin_cloaked.dmi
  icons/fallout/mobs/nightkin_dead.dmi
  icons/mob/actions/actions_items.dmi
  icons/mob/wastemobs.dmi
  icons/obj/device.dmi
  tgstation.dme
Labels: Balance/Rebalance, Bugfix, Code Change, Sprites & Spriting, enhancement

#10 Adds commies gimmick's armor and uniform.
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/f13.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites & Spriting, enhancement

#9 Role tweaks
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Balance/Rebalance, Tweak

#6 Kebab Remap, Chicken Ranch gone, 5 new buildings outside Kebab
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump.dmm
Labels: Balance/Rebalance, Mapping, Testmerged, good first issue

#12 Soviet gear's buff, craftable scavenger uniform and armor.
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/f13.dm
  code/modules/crafting/tailoring.dm
  config/admins.txt
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Balance/Rebalance, Sprites & Spriting, enhancement

#13 Adds german african uniform and craftable respirator, adjusts scavenger suit's armor values.
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/f13.dm
  code/modules/crafting/tailoring.dm
  icons/mob/mask.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
Labels: Sprites & Spriting, enhancement

#14 Explosive collar crafting.
  code/modules/crafting/recipes.dm
Labels: Code Change, Tweak
